name: DC motor SIL build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run SIL
        run: sh build-local.sh
